/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TaskCategory = IDL.Variant({
  'intermediate' : IDL.Null,
  'beginner' : IDL.Null,
  'advanced' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'isDaily' : IDL.Bool,
  'steps' : IDL.Vec(IDL.Text),
  'creditReward' : IDL.Nat,
  'category' : TaskCategory,
});
export const UserProfile = IDL.Record({
  'streak' : IDL.Nat,
  'lastActiveDay' : IDL.Int,
  'credits' : IDL.Nat,
  'username' : IDL.Text,
  'completedTaskIds' : IDL.Vec(IDL.Nat),
  'badges' : IDL.Vec(IDL.Text),
  'email' : IDL.Text,
  'level' : IDL.Nat,
});
export const ContactMessage = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTask' : IDL.Func(
      [IDL.Text, IDL.Text, TaskCategory, IDL.Nat, IDL.Vec(IDL.Text), IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeTask' : IDL.Func([IDL.Nat], [], []),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getDailyChallenge' : IDL.Func([], [IDL.Opt(Task)], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerOrUpdateProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setDailyChallenge' : IDL.Func([IDL.Nat], [], []),
  'submitContactMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TaskCategory = IDL.Variant({
    'intermediate' : IDL.Null,
    'beginner' : IDL.Null,
    'advanced' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'isDaily' : IDL.Bool,
    'steps' : IDL.Vec(IDL.Text),
    'creditReward' : IDL.Nat,
    'category' : TaskCategory,
  });
  const UserProfile = IDL.Record({
    'streak' : IDL.Nat,
    'lastActiveDay' : IDL.Int,
    'credits' : IDL.Nat,
    'username' : IDL.Text,
    'completedTaskIds' : IDL.Vec(IDL.Nat),
    'badges' : IDL.Vec(IDL.Text),
    'email' : IDL.Text,
    'level' : IDL.Nat,
  });
  const ContactMessage = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTask' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          TaskCategory,
          IDL.Nat,
          IDL.Vec(IDL.Text),
          IDL.Bool,
        ],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeTask' : IDL.Func([IDL.Nat], [], []),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
    'getDailyChallenge' : IDL.Func([], [IDL.Opt(Task)], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerOrUpdateProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setDailyChallenge' : IDL.Func([IDL.Nat], [], []),
    'submitContactMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };